# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
r:
  - release
warnings_are_errors: false
script:
  - R CMD build .
  - R CMD check *tar.gz --no-tests
notifications:
  email:
    - tomek@zozlak.org
    - t.zoltak@ibe.edu.pl
